"""Fill data

Revision ID: 1e7a277e248a
Revises: ca248cbd72c5
Create Date: 2024-01-10 14:45:43.886629

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e7a277e248a'
down_revision = 'ca248cbd72c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
