"""Price update

Revision ID: 322b1f9bbb78
Revises: 85284f46c805
Create Date: 2024-01-10 19:06:45.792619

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '322b1f9bbb78'
down_revision = '85284f46c805'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurants', sa.Column('price', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('restaurants', 'price')
    # ### end Alembic commands ###
