"""Fill data

Revision ID: 85284f46c805
Revises: 1e7a277e248a
Create Date: 2024-01-10 15:11:22.028052

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85284f46c805'
down_revision = '1e7a277e248a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
