"""Price update

Revision ID: b1b1d4b2ea10
Revises: 322b1f9bbb78
Create Date: 2024-01-10 19:53:49.594987

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1b1d4b2ea10'
down_revision = '322b1f9bbb78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
